server:
  port: ${PORT:8080}

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:

        - id: auth-service
          uri: ${AUTH_SERVICE_URL:lb://AUTH-SERVICE}
          predicates:
            - Path=/api/v1/auth/**

        - id: cliente-service
          uri: ${CLIENTE_SERVICE_URL:lb://CLIENTE-SERVICE}
          predicates:
            - Path=/api/v1/clientes/**

        - id: producto-service
          uri: ${PRODUCTO_SERVICE_URL:lb://PRODUCTO-SERVICE}
          predicates:
            - Path=/api/v1/productos/**

        - id: pedido-service
          uri: ${PEDIDO_SERVICE_URL:lb://PEDIDO-SERVICE}
          predicates:
            - Path=/api/v1/pedidos/**

        - id: pago-service
          uri: ${PAGO_SERVICE_URL:lb://PAGO-SERVICE}
          predicates:
            - Path=/api/v1/pagos/**

        - id: envio-service
          uri: ${ENVIO_SERVICE_URL:lb://ENVIO-SERVICE}
          predicates:
            - Path=/api/v1/envios/**

        - id: distribuidor-service
          uri: ${DISTRIBUIDOR_SERVICE_URL:lb://DISTRIBUIDOR-SERVICE}
          predicates:
            - Path=/api/v1/distribuidores/**

        - id: resena-service
          uri: ${RESENA_SERVICE_URL:lb://RESENA-SERVICE}
          predicates:
            - Path=/api/v1/resenas/**

        - id: sucursal-service
          uri: ${SUCURSAL_SERVICE_URL:lb://SUCURSAL-SERVICE}
          predicates:
            - Path=/api/v1/sucursales/**

        - id: trabajador-service
          uri: ${TRABAJADOR_SERVICE_URL:lb://TRABAJADOR-SERVICE}
          predicates:
            - Path=/api/v1/trabajadores/**

management:
  endpoint:
    gateway:
      access: read-only

  endpoints:
    web:
      exposure:
        include: health,info,gateway

eureka:
  client:
    enabled: ${EUREKA_ENABLED:true}
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

  instance:
    prefer-ip-address: true